### ISSUE TITLE
bug: possible out of bounds exception

### ISSUE THREAD

**Issue by ghost** [moistari/rls#3]
See:
https://github.com/moistari/rls/blob/4acc5f1e1c73d127bfce2088c604c91acb216437/lex.go#L185
https://github.com/moistari/rls/blob/4acc5f1e1c73d127bfce2088c604c91acb216437/lex.go#L229
https://github.com/moistari/rls/blob/4acc5f1e1c73d127bfce2088c604c91acb216437/lex.go#L341
https://github.com/moistari/rls/blob/4acc5f1e1c73d127bfce2088c604c91acb216437/lex.go#L369
https://github.com/moistari/rls/blob/4acc5f1e1c73d127bfce2088c604c91acb216437/lex.go#L412

**Comment by moistari** [comment]
@stacksmash76 thanks, but these are not potential out of bounds exceptions, as they use the string pairs returned from calling the returned `NamedCaptureLexer` func:

```
// NamedCaptureLexer returns a func that matches named capture groups,                                                                                                                      
// returning as name/value string pairs.
```
