### ISSUE TITLE
Incorrect parsing of collection

### ISSUE THREAD

**Issue by nuxencs** [moistari/rls#8]
The collection for this release should be `AMZN` but is getting parsed as `LIFE`.

https://go.dev/play/p/tlJ0b-sD_5B

**Comment by moistari** [comment]
thanks for bringing this up here -- in the future just copy/paste the actual release name here. a fix is incoming.

**Comment by nuxencs** [comment]
> thanks for bringing this up here -- in the future just copy/paste the actual release name here. a fix is incoming.

will do that in the future 👍 
greatly appreciate the quick fix!
